### ISSUE TITLE
Error while compiling for the ATmega88

### ISSUE THREAD

**Issue by ghost** [go4retro/PS2Encoder#1]
Hello,
I receive an error while compiling for the ATmega88 within the master branch.
The compiler said the he` CONFIG_UART_BAUDRATE` is not declared.
`#define UART0_BAUDRATE CONFIG_UART_BAUDRATE` from line 51 in config.h

**Comment by ghost** [comment]
Please close this issue. Don't know what happend after a git clone.
I pulled the repository again and now it's working fine.
Sorry for the noise,

**Comment by go4retro** [comment]
No worries!  I was definitely prepared that I'd broken the build for one of the targets.
